services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"



  promethues:
    image: prom/prometheus
    volumes:
      - .prometheus.yml:/etc/prometheus/prometheus.yml

    ports:
      - "9090:9090"